name: Publish Docker Image

on:
  push:
    branches: [ php73 ]
env:
  IMAGE_NAME: apache
  VERSION: v7.3
jobs:
  buildImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: image=moby/buildkit:master
      
      - name: log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN}}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: actions/checkout@v2
      - name: Build Container image
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --tag ghcr.io/nabad600/apache:v7.3 . --push